In [70]:
import pandas as pd
dataset=pd.read_excel('data.xlsx')
dataset=dataset.set_index('Tid')
dataset['Income']= dataset['Income'].str.strip('K')
dataset['Income']=dataset['Income'].astype('int')
dataset

    Refund Marital Status  Income Evade
Tid
1      Yes         Single     125    No
2       No        Married     100    No
3       No         Single      70    No
4      Yes        Married     120    No
5       No       Divorced      95   Yes
6       No        Married      60    No
7      Yes       Divorced     220    No
8       No         Single      85   Yes
9       No        Married      75    No
10      No         Single      90   Yes

In [71]:
import math 
def prob_cont(Income,mean,var):
    return((1/math.sqrt(2*math.pi*var))*(math.exp(-(((Income-mean)**2)/(2*var)))))

In [72]:
def Bayes(refund,status,income):
    
    
    # for Evade = Yes
    datasetyes = dataset[dataset['Evade'] == 'Yes']
   
    data_refund1 = datasetyes[datasetyes['Refund'] == refund]
    data_status1 = datasetyes[datasetyes['Marital Status'] == status]
    
    yes_var = datasetyes['Income'].var() 
    yes_mean = datasetyes['Income'].mean()

    prob_of_yes = datasetyes.shape[0] / dataset.shape[0] # yes
    prob_of_refund1 = data_refund1.shape[0] / datasetyes.shape[0]  # refund yes/no
    prob_of_status1 = data_status1.shape[0] / datasetyes.shape[0]  # status married/single/divorced
    prob_of_income1 = prob_cont(income,yes_mean,yes_var) # 90/60
    totalprob1=(prob_of_refund1*prob_of_status1*prob_of_income1)*prob_of_yes
    
    #for Evade = No
    datasetno = dataset[dataset['Evade'] == 'No']
    
    data_refund2 = datasetno[datasetno['Refund'] == refund] 
    data_status2 = datasetno[datasetno['Marital Status'] == status]
    
    no_var = datasetno['Income'].var() 
    no_mean = datasetno['Income'].mean()
    
    prob_of_no = datasetno.shape[0] / dataset.shape[0] # yes/no
    prob_of_refund2 = data_refund2.shape[0] / datasetno.shape[0]  # refund yes/no
    prob_of_status2 = data_status2.shape[0] / datasetno.shape[0]  # status married/single/divorced
    prob_of_income2 = prob_cont(income,no_mean,no_var)# 90/60
   
    totalprob2=(prob_of_refund2*prob_of_status2*prob_of_income2)*prob_of_no

    if(totalprob2>totalprob1):
        print("The Evade is No")
    else:
        print("The Evade is Yes")

In [73]:
Bayes('Yes','Divorced',90)
Bayes('No','Married',60)

The Evade is No
The Evade is No